version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  db-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql+pymysql://testuser:testpassword@mysql:3306/testdb
      GRPC_PORT: 50051
      LOG_LEVEL: INFO
    ports:
      - "50051:50051"

volumes:
  mysql_data:
