"""09_rename_user_person

Revision ID: 69670275a50e
Revises: 3a3b4b15dc93
Create Date: 2025-07-23 14:52:06.773773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69670275a50e'
down_revision: Union[str, None] = '3a3b4b15dc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('user', 'person')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('person', 'user')
    # ### end Alembic commands ###
