"""05_double_change_salary_integer

Revision ID: 856af1180d52
Revises: a1ddc5c3cd46
Create Date: 2025-07-23 13:14:30.199984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '856af1180d52'
down_revision: Union[str, None] = 'a1ddc5c3cd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'income',
        new_column_name='salary',
        existing_type=sa.String(length=100),
        type_=mysql.INTEGER(),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'salary',
        new_column_name='income',
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=100),
        existing_nullable=False)
    
    # ### end Alembic commands ###