"""06_email_default

Revision ID: 9ada530512f7
Revises: 856af1180d52
Create Date: 2025-07-23 13:17:17.357168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ada530512f7'
down_revision: Union[str, None] = '856af1180d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'user',
        'email',
        existing_type=sa.String(length=255),
        server_default='no-reply@example.com'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.alter_column(
        'user',
        'email',
        existing_type=sa.String(length=255),
        server_default=None
    )
    # ### end Alembic commands ###
