"""04_salary_to_income_namechange

Revision ID: a1ddc5c3cd46
Revises: cf22cea64162
Create Date: 2025-07-23 13:11:20.883143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import Column, Integer, BigInteger, String, Text, DateTime, Float, JSON, ForeignKey,text,CheckConstraint

# revision identifiers, used by Alembic.
revision: str = 'a1ddc5c3cd46'
down_revision: Union[str, None] = 'cf22cea64162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salary', new_column_name='income',type_=String(100))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'income', new_column_name='salary',type_=String(100))
    # ### end Alembic commands ###
