"""12_cross_table_FK

Revision ID: b88697d5c808
Revises: ce58f0750cd2
Create Date: 2025-07-23 15:05:09.435407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88697d5c808'
down_revision: Union[str, None] = 'ce58f0750cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key('FK_dept', 'person', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_dept', 'person', type_='foreignkey')
    op.drop_column('person', 'department_id')
    op.drop_table('department')
    # ### end Alembic commands ###
