"""11_same_table_FK

Revision ID: ce58f0750cd2
Revises: d296bb46b9e1
Create Date: 2025-07-23 15:02:03.856163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce58f0750cd2'
down_revision: Union[str, None] = 'd296bb46b9e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key('FK_manager', 'person', 'person', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_manager', 'person', type_='foreignkey')
    op.drop_column('person', 'manager_id')
    # ### end Alembic commands ###
