"""03_Salary_dtpye_change

Revision ID: cf22cea64162
Revises: bd9094356799
Create Date: 2025-07-23 13:08:56.536272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cf22cea64162'
down_revision: Union[str, None] = 'bd9094356799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salary',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'salary',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
